### ISSUE TITLE
Keep getting an exception

### ISSUE THREAD

**Issue by Pentasis** [kshetline/ligatures-limited-intellij#8] opened 2020-10-29 14:15 UTC
Hi, I keep getting an exception when running your plugin.
https://gist.github.com/Pentasis/0a77053bb5a61fbc086dd81b7d4132fb

**Comment by kshetline** [comment] 2020-10-30 17:16
Does this exception prevent the extension from working, or is it just a side effect with the extension still working anyway?

**Comment by kshetline** [comment] 2020-10-30 17:30
Having just looked at the line in my code where the exception is thrown, it looks like the extension wouldn't be working at all for you. But the issue is very strange. The exception is thrown on the first line of this code:
```
      for (language in LanguageUtil.getFileLanguages()) {
        val li = LanguageInfo(language, ++nextLanguageId)
        val id = language.idLc

        languageLookup[id] = li
        languageIndexLookup[nextLanguageId] = li
      }
    }
```
`LanguageUtil.getFileLanguages()` is nothing more than an IntelliJ method for listing available languages. The failure has to be somewhere inside IntelliJ itself, and I can't imagine why this would throw an exception.

I suppose I could try to work around the problem, by catching any exception that happens, and if one does happen, substituting a pre-defined language list. But it's odd that I'd need to do that.

Which IntelliJ product are you using? Can you think of anything unusual about your configuration or other extensions that might cause checking the list of available languages to fail?

**Comment by Pentasis** [comment] 2020-10-31 09:29
Hi,
I am using IntelliJ IDEA Community Edition 2020.2.3 with the following added plugins:
- Atom file Icons
- cmdsupport
- git machette
- git toolbox
- batch support
- gitignore
- ini4idea
- toml support
- JBehave
- Json editor
- Ligature Limited (yours)
- Minecraft development
- Minecraft NBT support
- Python community edition
- Shell script
- String manipulation

If I had to venture a guess I'd say perhaps the Minecraft plugins? As they are not widely used.

**Comment by kshetline** [comment] 2020-11-02 02:08
I've just submitted an update which will hopefully fix your problem. It should be available in a couple of days as long as nothing goes wrong with the JetBrains approval process.

Please let me know if it helps, whenever you can download it. Since I couldn't reproduce the bug myself it will be good to know for sure that my changes fixed the problem for you.

**Comment by kshetline** [comment] 2020-11-02 03:17
Since my update has passed the automated JetBrains checks, I made a release of those change available here, which are available now if you don't want to wait for the final JetBrains approval: https://github.com/kshetline/ligatures-limited-intellij/releases/tag/v1.0.2

You can download the extension and install it manually from the linked release above.

**Comment by kshetline** [comment] 2020-11-03 19:16
The updated plugin is now available in the JetBrains Marketplace, so you should be able to automatically update to the new version, without having to manually install it. I'll close this bug as fixed in a few days unless I hear otherwise from you.

**Comment by Pentasis** [comment] 2020-11-03 19:22
I got the update this afternoon. It seems to be fixed. Thank you.

**Comment by kshetline** [comment] 2020-11-03 23:57
Fixed.

**Closed as completed by kshetline** 2020-11-03 23:57 UTC

**Comment by tdtm** [comment] 2021-02-24 18:58
I'm getting the same stack trace in PhpStorm 2021.1 EAP. @kshetline would you like me to open a new issue?
